[project]
name = "service-2"
version = "0.1.0"
description = "Python Flask microservice"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.0.0",
]

[build-system]
requires = ["uv"]
build-backend = "uv.build"

[tool.uv]
python = "3.11"
